email: site@serai.exchange
name: Serai DEX
description: Serai DEX | Swap Bitcoin, Ethereum, DAI stablecoin, Monero, and more
keywords: ""
baseurl: ""
url: ""

markdown: kramdown

kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
    input: GFM

plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"
